//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DobraNutkaApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Albums
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Albums()
        {
            this.Orders = new HashSet<Orders>();
        }
    
        public int album_id { get; set; }
        public string album_title { get; set; }
        public Nullable<int> artist_id { get; set; }
        public Nullable<int> genre_id { get; set; }
        public Nullable<System.DateTime> release_date { get; set; }
        public Nullable<int> format_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
        public virtual Artists Artists { get; set; }
        public virtual Formats Formats { get; set; }
        public virtual Genres Genres { get; set; }
    }
}
