//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DobraNutkaApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class dobra_nutkaEntities : DbContext
    {
        public dobra_nutkaEntities()
            : base("name=dobra_nutkaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adresses> Adresses { get; set; }
        public virtual DbSet<Albums> Albums { get; set; }
        public virtual DbSet<Artists> Artists { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<Formats> Formats { get; set; }
        public virtual DbSet<Genres> Genres { get; set; }
        public virtual DbSet<Locations> Locations { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<Positions> Positions { get; set; }
    
        public virtual int addArtist(string name, Nullable<System.DateTime> birthday)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var birthdayParameter = birthday.HasValue ?
                new ObjectParameter("birthday", birthday) :
                new ObjectParameter("birthday", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("addArtist", nameParameter, birthdayParameter);
        }
    
        public virtual int addClients(string firstName, string lastName, string email, Nullable<System.DateTime> date)
        {
            var firstNameParameter = firstName != null ?
                new ObjectParameter("firstName", firstName) :
                new ObjectParameter("firstName", typeof(string));
    
            var lastNameParameter = lastName != null ?
                new ObjectParameter("lastName", lastName) :
                new ObjectParameter("lastName", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("addClients", firstNameParameter, lastNameParameter, emailParameter, dateParameter);
        }
    
        public virtual int addEmployee(string firstName, string lastName, Nullable<int> location, Nullable<System.DateTime> date, Nullable<int> position)
        {
            var firstNameParameter = firstName != null ?
                new ObjectParameter("firstName", firstName) :
                new ObjectParameter("firstName", typeof(string));
    
            var lastNameParameter = lastName != null ?
                new ObjectParameter("lastName", lastName) :
                new ObjectParameter("lastName", typeof(string));
    
            var locationParameter = location.HasValue ?
                new ObjectParameter("location", location) :
                new ObjectParameter("location", typeof(int));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(System.DateTime));
    
            var positionParameter = position.HasValue ?
                new ObjectParameter("position", position) :
                new ObjectParameter("position", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("addEmployee", firstNameParameter, lastNameParameter, locationParameter, dateParameter, positionParameter);
        }
    
        public virtual int addGenre(string name)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("addGenre", nameParameter);
        }
    
        public virtual int addMusicRecord(string title, Nullable<int> artist, Nullable<int> genre, Nullable<System.DateTime> date, Nullable<int> format)
        {
            var titleParameter = title != null ?
                new ObjectParameter("Title", title) :
                new ObjectParameter("Title", typeof(string));
    
            var artistParameter = artist.HasValue ?
                new ObjectParameter("Artist", artist) :
                new ObjectParameter("Artist", typeof(int));
    
            var genreParameter = genre.HasValue ?
                new ObjectParameter("Genre", genre) :
                new ObjectParameter("Genre", typeof(int));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(System.DateTime));
    
            var formatParameter = format.HasValue ?
                new ObjectParameter("Format", format) :
                new ObjectParameter("Format", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("addMusicRecord", titleParameter, artistParameter, genreParameter, dateParameter, formatParameter);
        }
    
        public virtual int addOrder(Nullable<int> client, Nullable<int> album, Nullable<int> employee, Nullable<int> location)
        {
            var clientParameter = client.HasValue ?
                new ObjectParameter("client", client) :
                new ObjectParameter("client", typeof(int));
    
            var albumParameter = album.HasValue ?
                new ObjectParameter("album", album) :
                new ObjectParameter("album", typeof(int));
    
            var employeeParameter = employee.HasValue ?
                new ObjectParameter("employee", employee) :
                new ObjectParameter("employee", typeof(int));
    
            var locationParameter = location.HasValue ?
                new ObjectParameter("location", location) :
                new ObjectParameter("location", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("addOrder", clientParameter, albumParameter, employeeParameter, locationParameter);
        }
    
        public virtual int removeEmployee(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("removeEmployee", idParameter);
        }
    
        public virtual int removeMusicRecord(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("removeMusicRecord", idParameter);
        }
    
        public virtual ObjectResult<retMusicRecord_Result> retMusicRecord(string title)
        {
            var titleParameter = title != null ?
                new ObjectParameter("title", title) :
                new ObjectParameter("title", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<retMusicRecord_Result>("retMusicRecord", titleParameter);
        }
    
        public virtual ObjectResult<showArtist_Result> showArtist()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<showArtist_Result>("showArtist");
        }
    
        public virtual ObjectResult<showClients_Result> showClients()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<showClients_Result>("showClients");
        }
    
        public virtual ObjectResult<showGenres_Result> showGenres()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<showGenres_Result>("showGenres");
        }
    
        public virtual ObjectResult<showLocations_Result> showLocations()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<showLocations_Result>("showLocations");
        }
    
        public virtual ObjectResult<showOrder_Result> showOrder()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<showOrder_Result>("showOrder");
        }
    
        public virtual ObjectResult<showPositions_Result> showPositions()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<showPositions_Result>("showPositions");
        }
    
        public virtual int uptadeMusicRecord(Nullable<int> id, string title, Nullable<int> artist, Nullable<int> genre, Nullable<System.DateTime> date, Nullable<int> format)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var titleParameter = title != null ?
                new ObjectParameter("Title", title) :
                new ObjectParameter("Title", typeof(string));
    
            var artistParameter = artist.HasValue ?
                new ObjectParameter("Artist", artist) :
                new ObjectParameter("Artist", typeof(int));
    
            var genreParameter = genre.HasValue ?
                new ObjectParameter("Genre", genre) :
                new ObjectParameter("Genre", typeof(int));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(System.DateTime));
    
            var formatParameter = format.HasValue ?
                new ObjectParameter("Format", format) :
                new ObjectParameter("Format", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uptadeMusicRecord", idParameter, titleParameter, artistParameter, genreParameter, dateParameter, formatParameter);
        }
    }
}
